openapi: 3.0.3
info:
  title: Arkivporten API
  version: 1.0.0
  description: API specification for Arkivporten (development placeholder).
servers:
  - url: https://arkivporten.ekstern.dev.nav.no
    description: Test documentation server
paths:
  /internal/api/v1:
    get:
      summary: Root of versioned API
      description: Placeholder endpoint returning Hello World or API metadata.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /:
    get:
      summary: Hello world
      description: Placeholder endpoint returning Hello World or API metadata.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas: {}
