### POST narmesteleder relasjon
POST http://localhost:8080/internal/api/v1/assets
Authorization: Bearer {{aad_token}}
Content-Type: application/json

{
  "assetId": "{{$random.uuid}}",
  "orgnumber": "{{orgnumber}}",
  "type": "OPPFOLGINGSPLAN",
  "pdf": "{{$random.alphabetic(100)}}"
}
