### POST document

POST http://localhost:8080/internal/api/v1/documents
Authorization: Bearer {{aad_token}}
Content-Type: application/json

{
  "documentId": "{{$random.uuid}}",
  "type": "OPPFOLGINGSPLAN",
  "content": "{{$random.alphabetic(100)}}",
  "contentType": "application/pdf",
  "orgNumber": "{{orgNumber}}",
  "dialogTitle": "Oppfølgingsplan",
  "dialogSummary": "Sykmeldt: Bjørn\nLeder: Daniel"
}
