apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arkivporten
  namespace: team-esyfo
  annotations:
    texas.nais.io/enabled: "true"
spec:
  ingresses:
    - https://arkivporten.intern.dev.nav.no
  image: {{image}} #
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  replicas:
    max: 2
    min: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        name: arkivporten-instance
        collation: nb_NO.UTF8
        databases:
          - name: arkivporten-db
            envVarPrefix: ARKIVPORTEN_DB
        diskAutoresize: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: syfo
          separator: "/"
          name: arkivporten
          atMaxAge: 680
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: nais
        - application: azure-token-generator
          namespace: nais
        - application: syfo-oppfolgingsplan-backend
          namespace: team-esyfo
        - application: isyfo-isdialogmote
          namespace: teamsykefravr
    outbound:
      rules:
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
      external:
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
  kafka:
    pool: nav-dev
  env:
    - name: EREG_BASE_URL
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: EREG_SCOPE
      value: dev-fss.arbeidsforhold.eareg-services-nais
    - name: ALTINN_TILGANGER_BASE_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
    - name: DIALOGPORTEN_SCOPE
      value: "digdir:dialogporten.serviceprovider"
