package no.nav.syfo.application.api

import io.github.tabilzad.ktor.annotations.GenerateOpenApi
import io.github.tabilzad.ktor.annotations.KtorDescription
import io.github.tabilzad.ktor.annotations.KtorResponds
import io.github.tabilzad.ktor.annotations.ResponseEntry
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import no.nav.syfo.application.ApplicationState
import no.nav.syfo.application.database.DatabaseInterface
import no.nav.syfo.application.isProdEnv
import no.nav.syfo.application.metric.registerMetricApi
import no.nav.syfo.dialogporten.client.IDialogportenClient
import no.nav.syfo.dialogporten.registerDialogportenTokenApi
import no.nav.syfo.document.db.DocumentDAO
import no.nav.syfo.document.service.ValidationService
import no.nav.syfo.registerApiV1
import no.nav.syfo.texas.client.TexasHttpClient
import org.koin.ktor.ext.inject

@GenerateOpenApi
fun Application.configureRouting() {
    val applicationState by inject<ApplicationState>()
    val database by inject<DatabaseInterface>()
    val texasHttpClient by inject<TexasHttpClient>()
    val documentDAO by inject<DocumentDAO>()
    val validationService by inject<ValidationService>()
    val dialogportenClient by inject<IDialogportenClient>()

    installCallId()
    installContentNegotiation()
    installStatusPages()

    routing {
        registerPodApi(applicationState, database)
        registerMetricApi()
        registerApiV1(texasHttpClient, documentDAO, validationService)
        if (!isProdEnv()) {
            // TODO: Remove this endpoint later
            registerDialogportenTokenApi(texasHttpClient, dialogportenClient)

            // Serve OpenAPI YAML specification
            get("/openapi.yaml") {
                val resource = this::class.java.classLoader.getResourceAsStream("openapi/openapi.yaml")
                if (resource != null) {
                    call.respondText(resource.bufferedReader().readText(), io.ktor.http.ContentType.Text.Plain)
                } else {
                    call.respondText("OpenAPI specification not found. Make sure to build the project first.", io.ktor.http.ContentType.Text.Plain)
                }
            }

            // Serve Swagger UI - generated by Inspektor plugin
            get("/swagger-ui") {
                call.respondText(
                    """
                    <!DOCTYPE html>
                    <html lang="en">
                    <head>
                        <meta charset="UTF-8">
                        <title>Arkivporten API Documentation</title>
                        <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.10.0/swagger-ui.css">
                    </head>
                    <body>
                        <div id="swagger-ui"></div>
                        <script src="https://unpkg.com/swagger-ui-dist@5.10.0/swagger-ui-bundle.js"></script>
                        <script>
                            window.onload = function() {
                                SwaggerUIBundle({
                                    url: '/openapi.yaml',
                                    dom_id: '#swagger-ui',
                                    deepLinking: true,
                                    presets: [
                                        SwaggerUIBundle.presets.apis,
                                        SwaggerUIBundle.SwaggerUIStandalonePreset
                                    ],
                                    layout: "BaseLayout"
                                })
                            }
                        </script>
                    </body>
                    </html>
                    """.trimIndent(),
                    io.ktor.http.ContentType.Text.Html
                )
            }
        }
        @KtorDescription(
            summary = "Hello World endpoint",
            description = "This endpoint will create an order",
        )
        @KtorResponds([ResponseEntry("200", String::class, isCollection=true, description = "Get hello world response")])
        get("/") {
            call.respondText("Hello World!")
        }
    }
}
